services:
  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: certicampus
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - /var/www/var/cache
      - /var/www/var/log
      - /var/www/vendor
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www:ro,cached
      - ./Docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php

volumes:
  db_data: