pipeline {
    agent any

    stages {
        stage('Build Docker') {
            steps {
                dir('backend') {
                    // On build les images proprement
                    sh 'docker-compose build'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'docker-compose up -d'
                    // Pas besoin de --working-dir si tu as mis working_dir dans le yaml
                    sh 'docker-compose exec -T php composer install --no-interaction --optimize-autoloader'
                }
            }
        }

        stage('Database Setup') {
            steps {
                dir('backend') {
                    // Attention au chemin de bin/console : il est à la racine de working_dir
                    sh 'docker-compose exec -T php php bin/console doctrine:database:create --if-not-exists'
                    sh 'docker-compose exec -T php php bin/console doctrine:migrations:migrate --no-interaction'
                }
            }
        }
    }

    post {
        always {
            script {
                try {
                    dir('backend') {
                        sh 'docker-compose down'
                    }
                } catch (Exception e) {
                    echo "Erreur lors du nettoyage : ${e.message}"
                }
            }
        }
    }
}